export { ipcChannels, type IpcChannel } from './constants/ipcChannels'
export type { DesktopApi } from './contracts/desktopApi'
export type { DesktopErrorCode, DesktopErrorShape } from './contracts/errors'
export type { DesktopFailure, DesktopResult, DesktopSuccess, VoidDesktopResult } from './types/desktop'
export type { WorkspaceConfig, WorkspaceParameters, WorkspaceStatus, WorkspaceSummary } from './types/workspace'
export type { TileGenerationRequest, TileGenerationResult } from './types/tile'
